name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24 
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      env:
        MAVEN_OPTS: "--enable-native-access=ALL-UNNAMED"
      run: mvn -B package --file pom.xml

    - name: Run Unit Tests
      env:
        MAVEN_OPTS: "--enable-native-access=ALL-UNNAMED"
      run: mvn test